config/routes.rb
Rails.application.routes.draw do
  # config/routes.rb
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :notes
    resources :beers
    resources :trucs
    resources :stores
    resources :directors
    devise_for :users
  end

  # root to: 'notes#index'
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'beers#index'
end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  value      :integer
#  beer_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#
class Note < ApplicationRecord
  belongs_to :beer
  MAX_VAL=10
  MIN_VAL=0

  validates :value, numericality: { in: MIN_VAL..MAX_VAL }

  def to_s
    value
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!

  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.where("user_id = ?", current_user.id)
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(I18n.locale, @note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(I18n.locale, @note), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy!

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
      
      unless @note.user_id == current_user.id
        redirect_to notes_url, alert: "Vous n'avez pas l'autorisation d'accéder à cette note."
      end 
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:value, :beer_id)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.haml
= form_with(model: note, class: "contents") do |form|
  - if note.errors.any?
    #error_explanation.bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
      %h2
        = pluralize(note.errors.count, "error")
        prohibited this note from being saved:
      %ul
        - note.errors.each do |error|
          %li= error.full_message

  .my-5
    = form.label :value
    = form.number_field :value, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :beer_id
    = form.select :beer_id, options_from_collection_for_select(Beer.all, "id", lambda { |beer| "#{beer.brand} - #{beer.name}" }), { prompt: "Select beer" }, { class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" }  
  .inline
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/notes/_note.html.haml
%div{:id => "#{dom_id note}"}
  %p.my-5
    %strong.block.font-medium.mb-1 Value:
    = note.value
  %p.my-5
    %strong.block.font-medium.mb-1 Beer:
    = note.beer.name
  - if action_name != "show"
    = link_to I18n.t('notes.show'), note, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    = link_to I18n.t('notes.edit'), edit_note_path(note), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
    %hr.mt-6/

app/views/notes/edit.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl Editing note
  = render "form", note: @note
  = link_to I18n.t('notes.show'), @note, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to I18n.t('notes.back'), notes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/notes/index.html.haml
.w-full
  - if notice.present?
    %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
  .flex.justify-between.items-center
    %h1.font-bold.text-4xl
      = I18n.t('notes.new')
    = link_to I18n.t('notes.new'), new_note_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"
  #notes.min-w-full
    = render @notes

app/views/notes/new.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl
    = I18n.t('notes.new')
  = render "form", note: @note
  = link_to I18n.t('notes.back'), notes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/notes/show.html.haml
.mx-auto.w-full.flex{:class => "md:w-2/3"}
  .mx-auto
    - if notice.present?
      %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
    = render @note
    = link_to I18n.t('notes.edit'), edit_note_path(@note), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    .inline-block.ml-2
      = button_to I18n.t('notes.destroy'), note_path(@note), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"
    = link_to I18n.t('notes.back'), notes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"