config/routes.rb
Rails.application.routes.draw do
  # config/routes.rb
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :notes
    resources :beers
    resources :trucs
    resources :stores
    resources :directors
    devise_for :users
  end

  # root to: 'notes#index'
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'beers#index'
end

app/models/store.rb
# == Schema Information
#
# Table name: stores
#
#  id         :integer          not null, primary key
#  name       :string
#  address    :string
#  city       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Store < ApplicationRecord
  has_and_belongs_to_many :beers

  belongs_to :director, required: false
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]

  # GET /stores or /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to store_url(I18n.locale, @store), notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to store_url(I18n.locale, @store), notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy!

    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:name, :address, :city, beer_ids: [])
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.haml
= form_with(model: store, class: "contents") do |form|
  - if store.errors.any?
    #error_explanation.bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
      %h2
        = pluralize(store.errors.count, "error")
        prohibited this store from being saved:
      %ul
        - store.errors.each do |error|
          %li= error.full_message
  .my-5
    = form.label :name
    = form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :address
    = form.text_field :address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :city
    = form.text_field :city, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :store_id
    -# = form.collection_select :store_id, Store.all, :id, :name, {:prompt => true}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
    = form.select :beer_ids, options_from_collection_for_select(Beer.all, "id", lambda { |beer| "#{beer.brand} - #{beer.name}" }), {:include_blank => false}, multiple: true, prompt: "Select beer", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .inline
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/stores/_store.html.haml
%div{:id => "#{dom_id store}"}
  %p.my-5
    %strong.block.font-medium.mb-1 Name:
    = store.name
  %p.my-5
    %strong.block.font-medium.mb-1 Address:
    = store.address
  %p.my-5
    %strong.block.font-medium.mb-1 City:
    = store.city
  %p.my-5
    %strong.block.font-medium.mb-1 Beers:
    - store.beer_ids.each do |beer_id|
      = "#{Beer.find(beer_id).brand} - #{Beer.find(beer_id).name}"

  - if action_name != "show"
    = link_to I18n.t('stores.show'), store, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    = link_to I18n.t('stores.edit'), edit_store_path(store), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
    %hr.mt-6/

app/views/stores/edit.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl Editing store
  = render "form", store: @store
  = link_to I18n.t('stores.show'), @store, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to I18n.t('stores.back'), stores_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/stores/index.html.haml
.w-full
  - if notice.present?
    %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
  .flex.justify-between.items-center
    %h1.font-bold.text-4xl
      = I18n.t 'stores.title'
    = link_to I18n.t('stores.new'), new_store_path(I18n.locale), class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"
  #stores.min-w-full
    = render @stores

app/views/stores/new.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl
    =I18n.t('stores.new')
  = render "form", store: @store
  = link_to I18n.t('stores.back'), stores_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/stores/show.html.haml
.mx-auto.w-full.flex{:class => "md:w-2/3"}
  .mx-auto
    - if notice.present?
      %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
    = render @store
    = link_to I18n.t('stores.edit'), edit_store_path(@store), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    .inline-block.ml-2
      = button_to I18n.t('stores.destroy'), store_path(@store), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"
    = link_to I18n.t('stores.back'), stores_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"