config/routes.rb
Rails.application.routes.draw do
  # config/routes.rb
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :notes
    resources :beers
    resources :trucs
    resources :stores
    resources :directors
    devise_for :users
  end

  # root to: 'notes#index'
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'beers#index'
end

app/models/director.rb
# == Schema Information
#
# Table name: directors
#
#  id         :integer          not null, primary key
#  firstName  :string
#  lastName   :string
#  store_id   :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Director < ApplicationRecord
  has_one :store
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: %i[ show edit update destroy ]

  # GET /directors or /directors.json
  def index
    @directors = Director.all
  end

  # GET /directors/1 or /directors/1.json
  def show
  end

  # GET /directors/new
  def new
    @director = Director.new
  end

  # GET /directors/1/edit
  def edit
  end

  # POST /directors or /directors.json
  def create
    @director = Director.new(director_params)

    respond_to do |format|
      if @director.save
        format.html { redirect_to director_url(I18n.locale, @director), notice: "Director was successfully created." }
        format.json { render :show, status: :created, location: @director }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directors/1 or /directors/1.json
  def update
    respond_to do |format|
      if @director.update(director_params)
        format.html { redirect_to director_url(I18n.locale, @director), notice: "Director was successfully updated." }
        format.json { render :show, status: :ok, location: @director }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @director.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directors/1 or /directors/1.json
  def destroy
    @director.destroy!

    respond_to do |format|
      format.html { redirect_to directors_url, notice: "Director was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_director
      @director = Director.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def director_params
      params.require(:director).permit(:firstName, :lastName, :store_id)
    end
end

app/helpers/directors_helper.rb
module DirectorsHelper
end

app/views/directors/_director.html.haml
%div{:id => "#{dom_id director}"}
  %p.my-5
    %strong.block.font-medium.mb-1 Firstname:
    = director.firstName
  %p.my-5
    %strong.block.font-medium.mb-1 Lastname:
    = director.lastName
  %p.my-5
    %strong.block.font-medium.mb-1 Store:
    = director.store_id
  - if action_name != "show"
    = link_to I18n.t('directors.show'), director, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    = link_to I18n.t('directors.edit'), edit_director_path(director), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
    %hr.mt-6/

app/views/directors/_form.html.haml
= form_with(model: director, class: "contents") do |form|
  - if director.errors.any?
    #error_explanation.bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
      %h2
        = pluralize(director.errors.count, "error")
        prohibited this director from being saved:
      %ul
        - director.errors.each do |error|
          %li= error.full_message
  .my-5
    = form.label :firstName
    = form.text_field :firstName, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :lastName
    = form.text_field :lastName, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :store_id
    = form.collection_select :store_id, Store.all, :id, :name, {:prompt => true}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
    -# = form.text_field :store_id, 
  .inline
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/directors/edit.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl Editing director
  = render "form", director: @director
  = link_to I18n.t('directors.show'), @director, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to I18n.t('directors.back'), directors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/directors/index.html.haml
.w-full
  - if notice.present?
    %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
  .flex.justify-between.items-center
    %h1.font-bold.text-4xl
      = I18n.t('directors.title')
    = link_to I18n.t('directors.new'), new_director_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"
  #directors.min-w-full
    = render @directors

app/views/directors/new.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl
    =I18n.t('directors.new')
  = render "form", director: @director
  = link_to I18n.t('directors.back'), directors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/directors/show.html.haml
.mx-auto.w-full.flex{:class => "md:w-2/3"}
  .mx-auto
    - if notice.present?
      %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
    = render @director
    = link_to I18n.t('directors.edit'), edit_director_path(@director), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    .inline-block.ml-2
      = button_to I18n.t('directors.destroy'), director_path(@director), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"
    = link_to I18n.t('directors.back'), directors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"