config/routes.rb
Rails.application.routes.draw do
  # config/routes.rb
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :notes
    resources :beers
    resources :trucs
    resources :stores
    resources :directors
    devise_for :users
  end

  # root to: 'notes#index'
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'beers#index'
end

app/models/beer.rb
# == Schema Information
#
# Table name: beers
#
#  id          :integer          not null, primary key
#  name        :string
#  cl          :float
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  brand       :string
#
class Beer < ApplicationRecord
  has_many :notes

  has_and_belongs_to_many :stores
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: %i[ show edit update destroy ]

  # GET /beers or /beers.json
  def index
    @beers = Beer.all
  end

  # GET /beers/1 or /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers or /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to beer_url(I18n.locale, @beer), notice: "Beer was successfully created." }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1 or /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to beer_url(I18n.locale, @beer), notice: "Beer was successfully updated." }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1 or /beers/1.json
  def destroy
    @beer.destroy!

    respond_to do |format|
      format.html { redirect_to beers_url, notice: "Beer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def beer_params
      params.require(:beer).permit(:name, :cl, :description, :brand)
    end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_beer.html.haml
%div{:id => "#{dom_id beer}"}
  %p.my-5
    %strong.block.font-medium.mb-1 Brand:
    = beer.brand
  %p.my-5
    %strong.block.font-medium.mb-1 Name:
    = beer.name
  %p.my-5
    %strong.block.font-medium.mb-1 Cl:
    = beer.cl
  %p.my-5
    %strong.block.font-medium.mb-1 Description:
    = beer.description
  %p.my-5
    %strong.block.font-medium.mb-1 Notes:
    = beer.notes.length > 0 ? beer.notes.pluck(:value).sum / beer.notes.length : 'None'

  - if action_name != "show"
    = link_to I18n.t('beers.show'), beer, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    = link_to I18n.t('beers.edit'), edit_beer_path(beer), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
    %hr.mt-6/

app/views/beers/_form.html.haml
= form_with(model: beer, class: "contents") do |form|
  - if beer.errors.any?
    #error_explanation.bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
      %h2
        = pluralize(beer.errors.count, "error")
        prohibited this beer from being saved:
      %ul
        - beer.errors.each do |error|
          %li= error.full_message
  .my-5
    = form.label :brand
    = form.text_field :brand, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :name
    = form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :cl
    = form.number_field :cl, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :description
    = form.text_field :description, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"

  .inline
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/beers/edit.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl Editing beer
  = render "form", beer: @beer
  = link_to I18n.t('beers.show'), @beer, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to I18n.t('beers.back'), beers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/beers/index.html.haml
.w-full
  - if notice.present?
    %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
  .flex.justify-between.items-center
    %h1.font-bold.text-4xl
      = I18n.t('beers.title')
    = link_to I18n.t('beers.new'), new_beer_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"
  #beers.min-w-full
    = render @beers

app/views/beers/new.html.haml
.mx-auto.w-full{:class => "md:w-2/3"}
  %h1.font-bold.text-4xl
    =I18n.t('beers.new')
  = render "form", beer: @beer
  = link_to I18n.t('beers.back'), beers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/beers/show.html.haml
.mx-auto.w-full.flex{:class => "md:w-2/3"}
  .mx-auto
    - if notice.present?
      %p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block= notice
    = render @beer
    = link_to I18n.t('beers.edit'), edit_beer_path(@beer), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    .inline-block.ml-2
      = button_to I18n.t('beers.destroy'), beer_path(@beer), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"
    = link_to I18n.t('beers.back'), beers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"